### ISSUE TITLE
The result of neutral.fit differs from other packages

### ISSUE THREAD

**Issue by lixiaopi1985** [Russel88/MicEco#28]
Hi Russel,

Thank you for the package.

As the title suggested, the R squared value differed from those of other packages, such as iCAMP's snm and reltools' fit_sncm when tested on the same dataset. 

> fit_sncm(t(data.frame(otu_table(OR16S_rare)))) # R2=0.4450697 m=0.1035867
> fit_sncm(t(data.frame(otu_table(VA16S_rare)))) # R2=0.3859323 m=0.0897298
> 
> snm(t(data.frame(otu_table(OR16S_rare)))) # R2=0.4450697 m=0.1035854
> snm(t(data.frame(otu_table(VA16S_rare)))) # R2=0.3859323 m=0.08973541
> 
> 
> neutral.fit(t(data.frame(otu_table(OR16S_rare)))) # R2=0.7925008 m=0.1035908
> neutral.fit(t(data.frame(otu_table(VA16S_rare)))) # R2=0.8073008 m=0.08970018

The R squared is about 0.3 to 0.4 more than the other two. I am new to modeling. Could you give me some insight on the differences?

Thank you,
Xiaoping

**Comment by Russel88** [comment]
Hi Xiaoping,

The underlying problem is that R-squared is not appropriate to use for non-linear models, like the neutral model. (See for example this paper: https://bmcpharma.biomedcentral.com/articles/10.1186/1471-2210-10-6)

iCAMP and reltools use the standard approach to calculating R squared (1-SS_res/SS_tot), but that is only valid for linear regressions. In MicEco I use the generalised R squared. I think the MicEco version is more appropriate, but neither are probably "correct".

**Comment by lixiaopi1985** [comment]
That makes sense. Thank you, Russel! 

Do you recommend rarefaction or any kind of transformation and normalization for amplicon data before fitting the neutral model?

**Comment by Russel88** [comment]
Yes, I think you need to rarefy, as the model uses the number of "Individuals" in each sample, which is assumed to be similar. The function (including that from reltools) just takes the mean read depth across samples as the number of individuals, and I am unsure how the model behaves if the read depths varies.

**Comment by lixiaopi1985** [comment]
Thank you so much!
