### ISSUE TITLE
Installation on R (4.0.4) - issue

### ISSUE THREAD

**Issue by SophiaNavis20** [Russel88/MicEco#6]
Hi, 

I'm trying to install the MicEco package using the command lines in R (version 4.0.4):

install.packages("remotes")
remotes::install_github("Russel88/MicEco")

But I got the following error message : " Error: Failed to install 'MicEco' from GitHub:
  Git does not seem to be installed on your system" 
 
Do you have any idea what should be the problem ?

Thank you for your time!

**Comment by Russel88** [comment]
The problem seems to be that you don't have Git installed on your computer. Since MicEco is installed through GitHub, you need Git to install it. You can find information on how to install Git here:
https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

If you're still having problems after installing Git, just let me know.

Regards,
Jakob

**Comment by SophiaNavis20** [comment]
Wonderful! It worked perfectly : -) 

Thanks
